### ISSUE TITLE
Track Meta as an Entity

### ISSUE THREAD

**Issue by joshua-stauffer** [joshua-stauffer/thehistoryatlas#63]
The `meta` field on `PublishNewCitation` commands represents a book or online resource. Track it as an entity with ID, and allow users to tag existing Meta entities instead of always creating a new one.

- [ ] ReadModel stores Meta as a searchable entity, and updates when receiving events
- [ ] ReadModel has gql endpoint to fuzzy search entity by name
- [x] WriteModel accepts meta tagged with an ID, or creates a new ID if new meta
- [ ] Client searches for matching meta as user inputs fields
- [ ] Client can send `PublishNewCitation` command with tagged meta
